import { StyleSheet } from "react-native";

import { Colors } from "./Colors";

export const createGlobalStyles = (theme: "light" | "dark") =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: Colors[theme].background,
    },
    background: {
      flex: 1,
      resizeMode: "cover",
    },
    screen: {
      flex: 1,
      backgroundColor: Colors[theme].background,
    },
    animation: {
      width: 150,
      height: 150,
    },
    title: {
      fontSize: 34,
      fontWeight: "800",
      marginTop: 10,
      marginBottom: 10,
      textAlign: "left",
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
      letterSpacing: 0,
    },
    subtitle: {
      fontSize: 23,
      fontWeight: "600",
      marginTop: 10,
      marginBottom: 10,
      textAlign: "center",
      fontFamily: "PoetsenOne",
      color: Colors[theme].text,
    },
    input: {
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].card,
      borderRadius: 8,
      padding: 18,
      fontSize: 16,
      marginBottom: 16,
      textAlign: "center",
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
    },
    image: {
      width: "100%",
      height: 150,
      borderRadius: 10,
    },
    imageCard: {
      width: "100%",
      height: 200,
      borderRadius: 10,
    },
    description: {
      fontSize: 18,
      color: Colors[theme].tint,
      marginTop: 4,
    },
    source: {
      fontSize: 10,
      color: Colors[theme].tabIconSelected,
      marginTop: 2,
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "space-around",
      marginBottom: 20,
    },
    button: {
      padding: 16,
      borderRadius: 8,
      flex: 1,
      marginHorizontal: 5,
      alignItems: "center",
    },
    buttonText: {
      color: Colors[theme].text,
      fontWeight: "600",
      fontSize: 18,
      fontFamily: "PoetsenOne",
      textAlign: "center",
    },
    emptyText: {
      fontSize: 16,
      textAlign: "center",
      color: Colors[theme].tabIconDefault,
      marginTop: 20,
      fontFamily: "PoetsenOne",
    },
    loader: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      color: Colors[theme].card,
    },
    error: {
      color: Colors[theme].not,
      textAlign: "center",
      marginBottom: 10,
    },
    errorText: {
      fontSize: 18,
      color: Colors[theme].not,
      textAlign: "center",
      borderRadius: 10,
      padding: 5,
      fontFamily: "PoetsenOne",
    },
    resultContainer: {
      alignItems: "center",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      paddingVertical: 50,
    },
    modalContent: {
      backgroundColor: Colors[theme].card,
      padding: 20,
      borderRadius: 10,
      alignItems: "center",
      width: "90%",
      maxHeight: "80%",
    },
    scrollContainer: {
      flexGrow: 1,
      width: "100%",
      maxHeight: "100%",
    },
    answerContainer: {
      marginBottom: 10,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: Colors[theme].border,
      width: "100%",
      alignItems: "center",
    },
    questionText: {
      fontSize: 18,
      fontWeight: "600",
      textAlign: "center",
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
    },
    quizContainer: {
      padding: 20,
      backgroundColor: Colors[theme].card,
      borderRadius: 10,
      shadowColor: Colors[theme].icon,
      shadowOpacity: 0.1,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 4,
      elevation: 5,
      textAlign: "center",
    },
    option: {
      padding: 25,
      borderRadius: 8,
      marginVertical: 5,
      alignItems: "center",
    },
    correctAnswer: {
      color: Colors[theme].ok,
    },
    wrongAnswer: {
      color: Colors[theme].not,
    },
    card: {
      backgroundColor: Colors[theme].card,
      borderRadius: 8,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      shadowColor: Colors[theme].shadow,
      shadowOpacity: 0.16,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 16,
      elevation: 4,
    },
    resultsContainer: {
      padding: 16,
      borderRadius: 8,
      backgroundColor: Colors[theme].card,
      marginTop: 20,
    },
    resultsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginVertical: 5,
    },
    resultText: {
      fontSize: 20,
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
    },
    settingRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginVertical: 10,
      padding: 10,
      backgroundColor: Colors[theme].card,
      borderRadius: 16,
    },
    picker: {
      height: 60,
      width: 150,
    },
    devInfo: {
      marginTop: 20,
      alignItems: "center",
      fontFamily: "PoetsenOne",
    },
    makesContainer: {
      flexGrow: 1,
      paddingBottom: 24,
      justifyContent: "flex-start",
    },
    makeButton: {
      backgroundColor: Colors[theme].surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      padding: 12,
      margin: 6,
      flex: 1,
      minWidth: 104,
      maxWidth: 120,
      height: 112,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: Colors[theme].shadow,
      shadowOpacity: 0.12,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: 3,
    },
    makeButtonText: {
      color: Colors[theme].text,
      fontSize: 14,
      fontWeight: "700",
      textAlign: "center",
    },
    makeAbbreviationText: {
      color: Colors[theme].icon,
      fontSize: 22,
      fontWeight: "800",
      textAlign: "center",
      marginBottom: 8,
    },
    pickerContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 10,
      paddingHorizontal: 10,
    },
    logo: {
      width: 72,
      height: 72,
      resizeMode: "contain",
    },
    favoriteIcon: {
      position: "absolute",
      top: 1,
      right: 1,
      backgroundColor: Colors[theme].card,
      borderRadius: 10,
      padding: 10,
    },
    adBannerContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: 16,
      minHeight: 50,
      width: "100%",
    },
    vinHero: {
      alignItems: "center",
      marginBottom: 6,
    },
    vinHint: {
      color: Colors[theme].text,
      fontSize: 15,
      lineHeight: 21,
      textAlign: "center",
      marginBottom: 12,
    },
    vinCounter: {
      color: Colors[theme].text,
      fontSize: 12,
      opacity: 0.72,
      textAlign: "center",
      marginTop: -10,
      marginBottom: 14,
    },
    vinResultsContainer: {
      padding: 16,
      borderRadius: 8,
      backgroundColor: Colors[theme].card,
      marginTop: 12,
      gap: 10,
    },
    vinResultHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    vinResultRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderTopWidth: 1,
      borderTopColor: Colors[theme].border,
      paddingTop: 10,
      gap: 12,
    },
    vinResultLabel: {
      color: Colors[theme].tint,
      fontSize: 14,
      flex: 1,
    },
    vinResultValue: {
      color: Colors[theme].text,
      fontSize: 16,
      fontWeight: "600",
      textAlign: "right",
      flex: 1,
      fontFamily: "PoetsenOne",
    },
    vinNextStep: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: Colors[theme].background,
      borderRadius: 8,
      padding: 10,
      marginTop: 4,
    },
    vinNextStepText: {
      color: Colors[theme].text,
      fontSize: 13,
      lineHeight: 18,
      flex: 1,
    },
  });

export const createHomeScreenStyles = (theme: "light" | "dark") =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors[theme].background,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 20,
      paddingTop: 14,
      paddingBottom: 112,
      backgroundColor: Colors[theme].background,
    },
    topBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    logo: {
      color: Colors[theme].icon,
      fontFamily: "BarlowCondensed_900Black",
      fontSize: 18,
      letterSpacing: 2.2,
      textTransform: "uppercase",
    },
    settingsButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].surface,
      alignItems: "center",
      justifyContent: "center",
    },
    hero: {
      backgroundColor: Colors[theme].surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      overflow: "hidden",
      minHeight: 214,
      marginBottom: 16,
      position: "relative",
    },
    heroInner: {
      paddingHorizontal: 22,
      paddingTop: 24,
      paddingBottom: 22,
      zIndex: 2,
    },
    heroEyebrowRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 12,
    },
    heroEyebrowLine: {
      width: 24,
      height: 1,
      backgroundColor: Colors[theme].accent,
    },
    eyebrow: {
      color: Colors[theme].accent,
      fontFamily: "DMSans_500Medium",
      fontSize: 10,
      letterSpacing: 2.6,
      textTransform: "uppercase",
    },
    heroTitle: {
      color: Colors[theme].text,
      fontFamily: "BarlowCondensed_900Black",
      fontSize: 62,
      lineHeight: 55,
      letterSpacing: 0.6,
    },
    heroAccent: {
      color: Colors[theme].accent,
    },
    heroSubtitle: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 12,
      lineHeight: 20,
      marginTop: 10,
      maxWidth: 210,
    },
    subtitle: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 14,
      lineHeight: 22,
      marginTop: 10,
    },
    heroCarOutline: {
      position: "absolute",
      right: -22,
      bottom: -58,
      opacity: theme === "dark" ? 0.1 : 0.07,
      transform: [{ scaleX: 1.15 }],
    },
    quickActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 14,
      marginBottom: 14,
    },
    quickAction: {
      backgroundColor: Colors[theme].surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 18,
      width: "48.2%",
      minHeight: 142,
      alignItems: "flex-start",
    },
    quickIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: Colors[theme].accentSoft,
      alignItems: "center",
      justifyContent: "center",
    },
    quickTitle: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 15,
      lineHeight: 19,
      marginTop: 22,
    },
    quickSubtitle: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 11,
      lineHeight: 16,
      marginTop: 5,
    },
    aiCard: {
      backgroundColor: Colors[theme].surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      padding: 16,
      minHeight: 250,
      marginBottom: 16,
    },
    aiHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    aiLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
    },
    aiLabelLine: {
      width: 16,
      height: 1,
      backgroundColor: Colors[theme].accent,
    },
    aiLabel: {
      color: Colors[theme].accent,
      fontFamily: "DMSans_500Medium",
      fontSize: 9,
      letterSpacing: 2.1,
      textTransform: "uppercase",
    },
    aiQuota: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 9,
      backgroundColor: Colors[theme].surfaceMuted,
      borderRadius: 100,
      paddingHorizontal: 8,
      paddingVertical: 3,
      overflow: "hidden",
    },
    aiPlaceholder: {
      color: Colors[theme].tabIconDefault,
      fontFamily: "DMSans_400Regular",
      fontSize: 14,
      lineHeight: 22,
      minHeight: 70,
    },
    aiFooter: {
      borderTopWidth: 1,
      borderTopColor: Colors[theme].border,
      paddingTop: 14,
      marginTop: "auto",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    aiChips: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      flex: 1,
    },
    aiChip: {
      borderWidth: 1,
      borderColor: Colors[theme].border,
      borderRadius: 100,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    aiChipText: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 11,
    },
    aiSendButton: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: Colors[theme].accent,
      alignItems: "center",
      justifyContent: "center",
    },
    buttonContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: 20,
    },
    button: {
      padding: 16,
      marginVertical: 10,
      borderRadius: 14,
      width: "80%",
      alignItems: "center",
      backgroundColor: Colors[theme].accent,
    },
    buttonText: {
      color: Colors[theme].text,
      fontSize: 15,
      fontWeight: "600",
      fontFamily: "DMSans_600SemiBold",
    },
  });
