import { StyleSheet } from "react-native";

import { Colors } from "./Colors";

export const createGlobalStyles = (theme: "light" | "dark") =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: Colors[theme].background,
      justifyContent: "center",
    },
    background: {
      flex: 1,
      resizeMode: "cover",
    },
    animation: {
      width: 150,
      height: 150,
    },
    title: {
      fontSize: 30,
      fontWeight: "600",
      marginTop: 10,
      marginBottom: 10,
      textAlign: "center",
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
      textShadowColor: "rgba(87, 87, 87, 0.7)",
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 3,
    },
    subtitle: {
      fontSize: 23,
      fontWeight: "600",
      marginTop: 10,
      marginBottom: 10,
      textAlign: "center",
      fontFamily: "PoetsenOne",
      color: Colors[theme].text,
    },
    input: {
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].card,
      borderRadius: 8,
      padding: 18,
      fontSize: 16,
      marginBottom: 16,
      textAlign: "center",
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
    },
    image: {
      width: "100%",
      height: 150,
      borderRadius: 10,
    },
    imageCard: {
      width: "100%",
      height: 200,
      borderRadius: 10,
    },
    description: {
      fontSize: 18,
      color: Colors[theme].tint,
      marginTop: 4,
    },
    source: {
      fontSize: 10,
      color: Colors[theme].tabIconSelected,
      marginTop: 2,
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "space-around",
      marginBottom: 20,
    },
    button: {
      padding: 16,
      borderRadius: 8,
      flex: 1,
      marginHorizontal: 5,
      alignItems: "center",
    },
    buttonText: {
      color: Colors[theme].text,
      fontWeight: "600",
      fontSize: 18,
      fontFamily: "PoetsenOne",
      textAlign: "center",
    },
    emptyText: {
      fontSize: 16,
      textAlign: "center",
      color: Colors[theme].tabIconDefault,
      marginTop: 20,
      fontFamily: "PoetsenOne",
    },
    loader: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      color: Colors[theme].card,
    },
    error: {
      color: Colors[theme].not,
      textAlign: "center",
      marginBottom: 10,
    },
    errorText: {
      fontSize: 18,
      color: Colors[theme].not,
      textAlign: "center",
      borderRadius: 10,
      padding: 5,
      fontFamily: "PoetsenOne",
    },
    resultContainer: {
      alignItems: "center",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      paddingVertical: 50,
    },
    modalContent: {
      backgroundColor: Colors[theme].card,
      padding: 20,
      borderRadius: 10,
      alignItems: "center",
      width: "90%",
      maxHeight: "80%",
    },
    scrollContainer: {
      flexGrow: 1,
      width: "100%",
      maxHeight: "100%",
    },
    answerContainer: {
      marginBottom: 10,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: Colors[theme].border,
      width: "100%",
      alignItems: "center",
    },
    questionText: {
      fontSize: 18,
      fontWeight: "600",
      textAlign: "center",
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
    },
    quizContainer: {
      padding: 20,
      backgroundColor: Colors[theme].card,
      borderRadius: 10,
      shadowColor: Colors[theme].icon,
      shadowOpacity: 0.1,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 4,
      elevation: 5,
      textAlign: "center",
    },
    option: {
      padding: 25,
      borderRadius: 8,
      marginVertical: 5,
      alignItems: "center",
    },
    correctAnswer: {
      color: Colors[theme].ok,
    },
    wrongAnswer: {
      color: Colors[theme].not,
    },
    card: {
      backgroundColor: Colors[theme].card,
      borderRadius: 10,
      padding: 16,
      marginBottom: 16,
      shadowRadius: 4,
    },
    resultsContainer: {
      padding: 16,
      borderRadius: 8,
      backgroundColor: Colors[theme].card,
      marginTop: 20,
    },
    resultsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginVertical: 5,
    },
    resultText: {
      fontSize: 20,
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
    },
    settingRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginVertical: 10,
      padding: 10,
      backgroundColor: Colors[theme].card,
      borderRadius: 16,
    },
    picker: {
      height: 60,
      width: 150,
    },
    devInfo: {
      marginTop: 20,
      alignItems: "center",
      fontFamily: "PoetsenOne",
    },
    makesContainer: {
      flexGrow: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    makeButton: {
      backgroundColor: Colors[theme].card,
      borderRadius: 10,
      padding: 15,
      margin: 5,
      width: 120,
      height: 120,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOpacity: 0.5,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 5,
    },
    makeButtonText: {
      color: Colors[theme].text,
      fontSize: 16,
      fontWeight: "600",
      textAlign: "center",
      fontFamily: "PoetsenOne",
    },
    pickerContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 10,
      paddingHorizontal: 10,
    },
    logo: {
      width: 80,
      height: 80,
      resizeMode: "contain",
    },
    favoriteIcon: {
      position: "absolute",
      top: 1,
      right: 1,
      backgroundColor: Colors[theme].card,
      borderRadius: 10,
      padding: 10,
    },
  });

export const createHomeScreenStyles = (theme: "light" | "dark") =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "center",
    },
    scrollContent: {
      flexGrow: 1,
      padding: 16,
      backgroundColor: "rgba(189, 189, 189, 0.43)",
      justifyContent: "center",
    },
    hero: {
      alignItems: "center",
      marginBottom: 14,
    },
    subtitle: {
      color: Colors[theme].text,
      fontSize: 16,
      lineHeight: 22,
      textAlign: "center",
      marginHorizontal: 12,
      fontFamily: "PoetsenOne",
    },
    statsRow: {
      alignItems: "center",
      marginBottom: 12,
    },
    statPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: Colors[theme].card,
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    statText: {
      color: Colors[theme].text,
      fontSize: 14,
      fontFamily: "PoetsenOne",
    },
    quickActions: {
      gap: 10,
    },
    quickAction: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: Colors[theme].card,
      borderRadius: 8,
      padding: 12,
      gap: 12,
    },
    quickIcon: {
      width: 42,
      height: 42,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    quickCopy: {
      flex: 1,
    },
    quickTitle: {
      color: Colors[theme].text,
      fontSize: 16,
      fontWeight: "600",
      fontFamily: "PoetsenOne",
    },
    quickSubtitle: {
      color: Colors[theme].text,
      fontSize: 12,
      lineHeight: 17,
      opacity: 0.78,
      marginTop: 2,
    },
    buttonContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: 20,
    },
    animation: {
      width: 300,
      height: 300,
    },
    button: {
      padding: 20,
      marginVertical: 10,
      borderRadius: 12,
      width: "80%",
      alignItems: "center",
    },
    buttonText: {
      color: Colors[theme].text,
      fontSize: 18,
      fontWeight: "600",
      fontFamily: "PoetsenOne",
    },
  });
