import { StyleSheet } from "react-native";

import { Colors } from "./Colors";

export const createGlobalStyles = (theme: "light" | "dark") =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: Colors[theme].background,
    },
    background: {
      flex: 1,
      resizeMode: "cover",
    },
    screen: {
      flex: 1,
      backgroundColor: "transparent",
    },
    flexFill: {
      flex: 1,
    },
    listContent: {
      paddingBottom: 128,
    },
    listContentWithStickyAction: {
      paddingBottom: 206,
    },
    centeredContent: {
      flexGrow: 1,
      justifyContent: "center",
      paddingHorizontal: 16,
      paddingBottom: 32,
    },
    animation: {
      width: 150,
      height: 150,
    },
    title: {
      fontSize: 24,
      fontWeight: "800",
      marginTop: 0,
      marginBottom: 16,
      textAlign: "left",
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
      letterSpacing: 0,
    },
    subtitle: {
      fontSize: 20,
      fontWeight: "600",
      marginTop: 10,
      marginBottom: 10,
      textAlign: "center",
      fontFamily: "PoetsenOne",
      color: Colors[theme].text,
    },
    input: {
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].card,
      borderRadius: 8,
      padding: 18,
      fontSize: 16,
      marginBottom: 16,
      textAlign: "center",
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
    },
    image: {
      width: "100%",
      height: 150,
      borderRadius: 10,
    },
    imageCard: {
      width: "100%",
      height: 200,
      borderRadius: 10,
    },
    imageFallback: {
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].surface,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    imageFallbackInitials: {
      color: Colors[theme].accent,
      fontFamily: "BarlowCondensed_900Black",
      fontSize: 54,
      lineHeight: 58,
      letterSpacing: 1.2,
      opacity: 0.45,
    },
    imageFallbackModel: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 13,
      marginTop: 4,
      maxWidth: "82%",
      textAlign: "center",
    },
    description: {
      fontSize: 18,
      color: Colors[theme].tint,
      marginTop: 4,
    },
    source: {
      fontSize: 10,
      color: Colors[theme].tabIconSelected,
      marginTop: 2,
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 10,
      marginBottom: 18,
    },
    button: {
      minHeight: 48,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 24,
      minWidth: 120,
      alignSelf: "stretch",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: Colors[theme].accent,
      borderWidth: 1,
      borderColor: "transparent",
      shadowColor: Colors[theme].shadow,
      shadowOpacity: 0.16,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 14,
      elevation: 4,
    },
    buttonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 14,
      fontFamily: "DMSans_600SemiBold",
      textAlign: "center",
    },
    buttonSecondaryText: {
      color: Colors[theme].text,
    },
    emptyText: {
      fontSize: 16,
      textAlign: "center",
      color: Colors[theme].tabIconDefault,
      marginTop: 20,
      fontFamily: "PoetsenOne",
    },
    loader: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      color: Colors[theme].card,
    },
    error: {
      color: Colors[theme].not,
      textAlign: "center",
      marginBottom: 10,
    },
    errorText: {
      fontSize: 18,
      color: Colors[theme].not,
      textAlign: "center",
      borderRadius: 10,
      padding: 5,
      fontFamily: "PoetsenOne",
    },
    resultContainer: {
      alignItems: "center",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      paddingHorizontal: 18,
      paddingVertical: 28,
    },
    modalBackdropPressable: {
      ...StyleSheet.absoluteFillObject,
    },
    modalContent: {
      backgroundColor: Colors[theme].card,
      padding: 18,
      borderRadius: 8,
      alignItems: "center",
      width: "100%",
      maxHeight: "74%",
      borderWidth: 1,
      borderColor: Colors[theme].border,
    },
    confirmModalContent: {
      backgroundColor: Colors[theme].card,
      padding: 20,
      borderRadius: 10,
      width: "88%",
      borderWidth: 1,
      borderColor: Colors[theme].border,
    },
    confirmModalTitle: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 20,
      lineHeight: 26,
      textAlign: "center",
    },
    confirmModalMessage: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 14,
      lineHeight: 22,
      textAlign: "center",
      marginTop: 12,
    },
    confirmModalActions: {
      flexDirection: "row",
      gap: 10,
      marginTop: 20,
    },
    confirmModalButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    confirmModalCancel: {
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].surface,
    },
    confirmModalCancelText: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 14,
    },
    confirmModalConfirmText: {
      color: "#fff",
      fontFamily: "DMSans_600SemiBold",
      fontSize: 14,
    },
    aboutModalContent: {
      backgroundColor: Colors[theme].card,
      padding: 22,
      borderRadius: 10,
      width: "88%",
      borderWidth: 1,
      borderColor: Colors[theme].border,
      alignItems: "center",
    },
    aboutModalIcon: {
      width: 48,
      height: 48,
      borderRadius: 8,
      backgroundColor: Colors[theme].accentSoft,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 14,
    },
    aboutModalDescription: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 14,
      lineHeight: 22,
      textAlign: "center",
      marginTop: 10,
    },
    aboutModalMeta: {
      width: "100%",
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: Colors[theme].border,
      paddingVertical: 14,
      marginVertical: 16,
      gap: 6,
    },
    aboutModalLabel: {
      color: Colors[theme].text,
      fontFamily: "DMSans_500Medium",
      fontSize: 13,
      textAlign: "center",
    },
    aboutModalCopyright: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 11,
      textAlign: "center",
    },
    aboutModalLink: {
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      marginBottom: 12,
    },
    aboutModalLinkText: {
      color: Colors[theme].accent,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 14,
    },
    scrollContainer: {
      width: "100%",
      maxHeight: "100%",
    },
    modalScrollContent: {
      paddingBottom: 16,
      alignItems: "center",
    },
    answerContainer: {
      marginBottom: 10,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: Colors[theme].border,
      width: "100%",
      alignItems: "center",
    },
    questionText: {
      fontSize: 18,
      fontWeight: "600",
      textAlign: "center",
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
    },
    quizContainer: {
      padding: 20,
      backgroundColor: Colors[theme].card,
      borderRadius: 10,
      shadowColor: Colors[theme].icon,
      shadowOpacity: 0.1,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 4,
      elevation: 5,
      textAlign: "center",
    },
    option: {
      padding: 25,
      borderRadius: 8,
      marginVertical: 5,
      alignItems: "center",
    },
    correctAnswer: {
      color: Colors[theme].ok,
    },
    wrongAnswer: {
      color: Colors[theme].not,
    },
    card: {
      backgroundColor: Colors[theme].card,
      borderRadius: 8,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      shadowColor: Colors[theme].shadow,
      shadowOpacity: 0.16,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 16,
      elevation: 4,
    },
    resultsContainer: {
      padding: 16,
      borderRadius: 8,
      backgroundColor: Colors[theme].card,
      marginTop: 20,
    },
    resultsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginVertical: 5,
    },
    resultText: {
      fontSize: 20,
      color: Colors[theme].text,
      fontFamily: "PoetsenOne",
    },
    settingRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginVertical: 10,
      padding: 10,
      backgroundColor: Colors[theme].card,
      borderRadius: 16,
    },
    settingLabel: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 15,
    },
    picker: {
      height: 60,
      width: 150,
    },
    devInfo: {
      marginTop: 20,
      alignItems: "center",
      fontFamily: "PoetsenOne",
    },
    makesContainer: {
      flexGrow: 1,
      paddingBottom: 120,
      justifyContent: "flex-start",
    },
    makeButton: {
      backgroundColor: Colors[theme].surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      padding: 12,
      margin: 6,
      flex: 1,
      minWidth: 104,
      maxWidth: 120,
      height: 112,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: Colors[theme].shadow,
      shadowOpacity: 0.12,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: 3,
    },
    makeButtonText: {
      color: Colors[theme].text,
      fontSize: 14,
      fontWeight: "700",
      textAlign: "center",
    },
    makeAbbreviationText: {
      color: Colors[theme].icon,
      fontSize: 22,
      fontWeight: "800",
      textAlign: "center",
      marginBottom: 8,
    },
    pickerContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 10,
      paddingHorizontal: 10,
    },
    logo: {
      width: 72,
      height: 72,
      resizeMode: "contain",
    },
    favoriteIcon: {
      position: "absolute",
      top: 10,
      right: 10,
      width: 42,
      height: 42,
      backgroundColor:
        theme === "dark" ? "rgba(10,10,11,0.88)" : "rgba(255,255,255,0.9)",
      borderRadius: 21,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      alignItems: "center",
      justifyContent: "center",
    },
    compareCardIconButton: {
      position: "absolute",
      top: 10,
      left: 10,
      width: 42,
      height: 42,
      borderRadius: 21,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor:
        theme === "dark" ? "rgba(10,10,11,0.88)" : "rgba(255,255,255,0.9)",
      alignItems: "center",
      justifyContent: "center",
    },
    compareCardIconButtonSelected: {
      backgroundColor: Colors[theme].accent,
      borderColor: Colors[theme].accent,
    },
    compareFloatingBar: {
      position: "absolute",
      left: 16,
      right: 16,
      zIndex: 10,
      minHeight: 58,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor:
        theme === "dark" ? "rgba(17,17,20,0.98)" : "rgba(255,255,255,0.98)",
      shadowColor: Colors[theme].shadow,
      shadowOpacity: 0.24,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 20,
      elevation: 16,
      padding: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    compareFloatingText: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 13,
      flex: 1,
    },
    compareFloatingButton: {
      minHeight: 40,
      borderRadius: 20,
      backgroundColor: Colors[theme].accent,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    compareFloatingButtonText: {
      color: "#fff",
      fontFamily: "DMSans_600SemiBold",
      fontSize: 13,
    },
    compareContent: {
      flexGrow: 1,
      paddingHorizontal: 20,
      paddingTop: 18,
      paddingBottom: 150,
      backgroundColor: "transparent",
    },
    compareEmptyStateWrapper: {
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 16,
      minHeight: 520,
    },
    compareBackButton: {
      alignSelf: "flex-start",
      minHeight: 40,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].surface,
      paddingHorizontal: 12,
      marginBottom: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    compareBackText: {
      color: Colors[theme].text,
      fontFamily: "DMSans_500Medium",
      fontSize: 12,
    },
    compareEyebrow: {
      color: Colors[theme].accent,
      fontFamily: "DMSans_500Medium",
      fontSize: 10,
      letterSpacing: 2.2,
      textTransform: "uppercase",
    },
    compareEmptyCard: {
      backgroundColor: Colors[theme].surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      padding: 20,
      marginTop: 16,
      alignItems: "center",
      gap: 12,
    },
    compareEmptyTitle: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 20,
      textAlign: "center",
    },
    compareEmptyText: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 14,
      lineHeight: 21,
      textAlign: "center",
    },
    comparePrimaryButton: {
      minHeight: 44,
      borderRadius: 22,
      backgroundColor: Colors[theme].accent,
      paddingHorizontal: 18,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 4,
    },
    comparePrimaryButtonText: {
      color: "#fff",
      fontFamily: "DMSans_600SemiBold",
      fontSize: 14,
    },
    compareHeaderGrid: {
      flexDirection: "row",
      gap: 10,
      marginTop: 12,
      marginBottom: 14,
    },
    compareCarHeader: {
      flex: 1,
      minHeight: 112,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].surface,
      padding: 12,
      justifyContent: "flex-end",
    },
    compareCarMake: {
      color: Colors[theme].accent,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 12,
      textTransform: "uppercase",
    },
    compareCarModel: {
      color: Colors[theme].text,
      fontFamily: "BarlowCondensed_800ExtraBold",
      fontSize: 26,
      lineHeight: 28,
    },
    compareRemoveButton: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      alignItems: "center",
      justifyContent: "center",
    },
    compareRow: {
      marginBottom: 12,
    },
    compareRowLabel: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 10,
      letterSpacing: 1.5,
      textTransform: "uppercase",
      textAlign: "center",
      marginBottom: 6,
    },
    compareValueGrid: {
      flexDirection: "row",
      gap: 10,
    },
    compareValueCell: {
      flex: 1,
      minHeight: 54,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].card,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 8,
    },
    compareValueText: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 14,
      textAlign: "center",
    },
    compareGhostButton: {
      minHeight: 44,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 8,
      marginBottom: 120,
    },
    compareGhostButtonText: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 14,
    },
    adBannerContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: 16,
      minHeight: 50,
      width: "100%",
    },
    vinHero: {
      alignItems: "center",
      marginBottom: 6,
    },
    vinHint: {
      color: Colors[theme].text,
      fontSize: 15,
      lineHeight: 21,
      textAlign: "center",
      marginBottom: 12,
    },
    vinCounter: {
      color: Colors[theme].text,
      fontSize: 12,
      opacity: 0.72,
      textAlign: "center",
      marginTop: -10,
      marginBottom: 14,
    },
    vinResultsContainer: {
      padding: 16,
      borderRadius: 8,
      backgroundColor: Colors[theme].card,
      marginTop: 12,
      marginBottom: 120,
      gap: 10,
    },
    stickyFooter: {
      paddingTop: 10,
      paddingBottom: 112,
      backgroundColor: "transparent",
    },
    stickyNavFooter: {
      position: "absolute",
      left: 20,
      right: 20,
      zIndex: 9,
      backgroundColor: "transparent",
    },
    pickerModalContent: {
      backgroundColor: Colors[theme].card,
      borderRadius: 8,
      width: "90%",
      maxHeight: "68%",
      borderWidth: 1,
      borderColor: Colors[theme].border,
      overflow: "hidden",
    },
    pickerOptionsScroll: {
      width: "100%",
    },
    pickerOptionsContent: {
      paddingBottom: 8,
    },
    pickerModalHeader: {
      minHeight: 54,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: Colors[theme].border,
    },
    pickerModalTitle: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 16,
    },
    pickerModalCloseText: {
      color: Colors[theme].accent,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 13,
    },
    pickerOption: {
      minHeight: 48,
      paddingHorizontal: 18,
      alignItems: "center",
      justifyContent: "center",
      borderBottomWidth: 1,
      borderBottomColor: Colors[theme].border,
    },
    pickerOptionSelected: {
      backgroundColor: Colors[theme].accentSoft,
    },
    pickerOptionText: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 15,
      textAlign: "center",
    },
    pickerTrigger: {
      minHeight: 44,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].surface,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    pickerTriggerText: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 13,
      textAlign: "center",
    },
    vinResultHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    vinResultRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderTopWidth: 1,
      borderTopColor: Colors[theme].border,
      paddingTop: 10,
      gap: 12,
    },
    vinResultLabel: {
      color: Colors[theme].tint,
      fontSize: 14,
      flex: 1,
    },
    vinResultValue: {
      color: Colors[theme].text,
      fontSize: 16,
      fontWeight: "600",
      textAlign: "right",
      flex: 1,
      fontFamily: "PoetsenOne",
    },
    vinNextStep: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: Colors[theme].background,
      borderRadius: 8,
      padding: 10,
      marginTop: 4,
    },
    vinNextStepText: {
      color: Colors[theme].text,
      fontSize: 13,
      lineHeight: 18,
      flex: 1,
    },
  });

export const createHomeScreenStyles = (theme: "light" | "dark") =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "transparent",
      paddingHorizontal: 20,
      paddingTop: 14,
      paddingBottom: 96,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 20,
      paddingTop: 14,
      paddingBottom: 112,
      backgroundColor: "transparent",
    },
    topBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    logo: {
      color: Colors[theme].icon,
      fontFamily: "BarlowCondensed_900Black",
      fontSize: 18,
      letterSpacing: 2.2,
      textTransform: "uppercase",
    },
    settingsButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 1,
      borderColor:
        theme === "dark" ? "rgba(255,77,28,0.38)" : "rgba(224,58,10,0.28)",
      backgroundColor:
        theme === "dark" ? "rgba(255,77,28,0.12)" : "rgba(224,58,10,0.10)",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: Colors[theme].accent,
      shadowOpacity: 0.16,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 10,
      elevation: 2,
    },
    hero: {
      backgroundColor:
        theme === "dark" ? "rgba(17,17,20,0.94)" : "rgba(255,255,255,0.82)",
      borderRadius: 20,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      overflow: "hidden",
      minHeight: 214,
      marginBottom: 16,
      position: "relative",
    },
    heroInner: {
      paddingHorizontal: 22,
      paddingTop: 24,
      paddingBottom: 22,
      zIndex: 2,
    },
    heroEyebrowRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 12,
    },
    heroEyebrowLine: {
      width: 24,
      height: 1,
      backgroundColor: Colors[theme].accent,
    },
    eyebrow: {
      color: Colors[theme].accent,
      fontFamily: "DMSans_500Medium",
      fontSize: 10,
      letterSpacing: 2.6,
      textTransform: "uppercase",
    },
    heroTitle: {
      color: Colors[theme].text,
      fontFamily: "BarlowCondensed_900Black",
      fontSize: 62,
      lineHeight: 55,
      letterSpacing: 0.6,
    },
    heroAccent: {
      color: Colors[theme].accent,
    },
    heroSubtitle: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 12,
      lineHeight: 20,
      marginTop: 10,
      maxWidth: 210,
    },
    subtitle: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 14,
      lineHeight: 22,
      marginTop: 10,
    },
    heroCarLine: {
      position: "absolute",
      right: -58,
      bottom: -2,
      width: 312,
      height: 104,
      opacity: theme === "dark" ? 0.32 : 0.22,
    },
    quickActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 14,
      marginBottom: 14,
    },
    quickAction: {
      backgroundColor:
        theme === "dark" ? "rgba(17,17,20,0.96)" : "rgba(255,255,255,0.84)",
      borderRadius: 16,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 18,
      width: "48.2%",
      minHeight: 142,
      alignItems: "flex-start",
      shadowColor: Colors[theme].shadow,
      shadowOpacity: theme === "dark" ? 0.18 : 0.1,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 16,
      elevation: 3,
    },
    quickIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: Colors[theme].accentSoft,
      alignItems: "center",
      justifyContent: "center",
    },
    quickTitle: {
      color: Colors[theme].text,
      fontFamily: "DMSans_600SemiBold",
      fontSize: 15,
      lineHeight: 19,
      marginTop: 22,
    },
    quickSubtitle: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 11,
      lineHeight: 16,
      marginTop: 5,
    },
    aiCard: {
      backgroundColor:
        theme === "dark" ? "rgba(17,17,20,0.96)" : "rgba(255,255,255,0.86)",
      borderRadius: 20,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      padding: 16,
      minHeight: 250,
      marginBottom: 16,
      shadowColor: Colors[theme].shadow,
      shadowOpacity: theme === "dark" ? 0.2 : 0.1,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 18,
      elevation: 3,
    },
    aiHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    aiLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
    },
    aiLabelLine: {
      width: 16,
      height: 1,
      backgroundColor: Colors[theme].accent,
    },
    aiLabel: {
      color: Colors[theme].accent,
      fontFamily: "DMSans_500Medium",
      fontSize: 9,
      letterSpacing: 2.1,
      textTransform: "uppercase",
    },
    aiQuota: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 9,
      backgroundColor: Colors[theme].surfaceMuted,
      borderRadius: 100,
      paddingHorizontal: 8,
      paddingVertical: 3,
      overflow: "hidden",
    },
    aiPlaceholder: {
      color: Colors[theme].tabIconDefault,
      fontFamily: "DMSans_400Regular",
      fontSize: 14,
      lineHeight: 22,
      minHeight: 70,
    },
    aiInput: {
      color: Colors[theme].text,
      fontFamily: "DMSans_400Regular",
      fontSize: 16,
      lineHeight: 22,
      minHeight: 72,
      textAlignVertical: "top",
      paddingVertical: 0,
      paddingHorizontal: 0,
    },
    aiAnswerCard: {
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors[theme].border,
      backgroundColor: Colors[theme].surfaceMuted,
      padding: 12,
      marginTop: 12,
    },
    aiAnswerText: {
      color: Colors[theme].text,
      fontFamily: "DMSans_400Regular",
      fontSize: 13,
      lineHeight: 20,
    },
    aiFooter: {
      borderTopWidth: 1,
      borderTopColor: Colors[theme].border,
      paddingTop: 14,
      marginTop: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    aiChips: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      flex: 1,
    },
    aiChip: {
      borderWidth: 1,
      borderColor: Colors[theme].border,
      borderRadius: 100,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    aiChipText: {
      color: Colors[theme].icon,
      fontFamily: "DMSans_400Regular",
      fontSize: 11,
    },
    aiSendButton: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: Colors[theme].accent,
      alignItems: "center",
      justifyContent: "center",
    },
    buttonContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: 20,
    },
    button: {
      padding: 16,
      marginVertical: 10,
      borderRadius: 14,
      width: "80%",
      alignItems: "center",
      backgroundColor: Colors[theme].accent,
    },
    buttonText: {
      color: Colors[theme].text,
      fontSize: 15,
      fontWeight: "600",
      fontFamily: "DMSans_600SemiBold",
    },
  });
